### ISSUE TITLE
Repository examples

### ISSUE THREAD

**Issue by junglie85** [lgiordani/rentomatic#3]
Great article and example code. In the article, you mentioned that you'd be writing a second post covering repositories with external databases. I didn't see anything on the blog to follow up this excellent post, did you ever get around to writing it? If not, any recommended reading for how to implement these (postgres/sqlalchemy ideally, but any external repo will do for a good example)?

**Comment by lgiordani** [comment]
Unfortunately I don't have handy other readings. I didn't read yet the Clean Architecture book by Robert Martin, so I don't know if it is good or not. At the moment the post covering repositories is scheduled for the future but I didn't write anything, sorry. I'll keep this issue open so I can keep you updated, however. Thanks

**Comment by lgiordani** [comment]
Hi! I finally have a solution for this issue. I added the chapter on Database Repositories to the "Clean Architectures in Python" free book that I published with Leanpub. I actually have to thank you, because I added that chapter having this issue in mind. Thanks!
